// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using buyyu.Data;

namespace buyyu.Data.Migrations
{
    [DbContext(typeof(BuyyuDbContext))]
    [Migration("20210301165318_State-Owned-Type")]
    partial class StateOwnedType
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("buyyu.Domain.Order.OrderRoot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("buyyu.Domain.Order.Orderline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderLines");
                });

            modelBuilder.Entity("buyyu.Domain.Order.Ref.OrderState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OrderStates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bd8be3d2-8028-45e2-a211-bf737a2508c1"),
                            Name = "Initiated",
                            ShortCode = "NEW"
                        },
                        new
                        {
                            Id = new Guid("82d9ce01-9f25-48b1-8af3-93f52426676f"),
                            Name = "Confirmed",
                            ShortCode = "CNF"
                        },
                        new
                        {
                            Id = new Guid("4b5549bb-b1b2-4964-9818-da984baab4ff"),
                            Name = "Shipped",
                            ShortCode = "SHP"
                        });
                });

            modelBuilder.Entity("buyyu.Domain.Payment.PaymentRoot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PayDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("buyyu.Domain.Product.ProductRoot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QtyInStock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("de679c55-4c13-4fe7-91b4-69cbce3223a2"),
                            Description = "Implement an ergonomic seating solution for your office with this maroon multipurpose chair. The included tilt tension knob lets you calibrate the tilt and recline resistance to your desired configuration, while the adjustable seat and armrests optimize your seating position for correct posture.",
                            Name = "Office Chair Beta",
                            Price = 169m,
                            QtyInStock = 213
                        },
                        new
                        {
                            Id = new Guid("32f75bce-16a0-4070-9fac-4289678c191f"),
                            Description = "The Lockland Big & Tall bonded leather managers chair offers top quality comfort, multiple adjustment features.",
                            Name = "Office Chair Manager",
                            Price = 263m,
                            QtyInStock = 75
                        },
                        new
                        {
                            Id = new Guid("bcbc1851-6317-4022-be62-53d29c04bcda"),
                            Description = "Carve out a personal workspace with this storage desk. The simple design and classic mid-century modern details make this desk perfect for modern decor themes or casual open office settings, and the rectangular desktop provides space for a laptop and peripherals.",
                            Name = "Vintage Desk",
                            Price = 305m,
                            QtyInStock = 179
                        },
                        new
                        {
                            Id = new Guid("5ca659b1-25b1-45c1-9755-3a3cd8591b9e"),
                            Description = "The Techni Mobili Complete Workstation Desk is everything you need in a computer desk and stay organized.",
                            Name = "Desk Techni",
                            Price = 295m,
                            QtyInStock = 150
                        });
                });

            modelBuilder.Entity("buyyu.Domain.Order.OrderRoot", b =>
                {
                    b.OwnsOne("buyyu.Domain.Order.OrderState", "State", b1 =>
                        {
                            b1.Property<Guid>("OrderRootId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("State");

                            b1.HasKey("OrderRootId");

                            b1.ToTable("Orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderRootId");
                        });

                    b.Navigation("State");
                });

            modelBuilder.Entity("buyyu.Domain.Order.Orderline", b =>
                {
                    b.HasOne("buyyu.Domain.Order.OrderRoot", "Order")
                        .WithMany("Lines")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("buyyu.Domain.Product.ProductRoot", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("buyyu.Domain.Payment.PaymentRoot", b =>
                {
                    b.HasOne("buyyu.Domain.Order.OrderRoot", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("buyyu.Domain.Order.OrderRoot", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
